### ISSUE TITLE
Select String needs a new entry

### ISSUE THREAD

**Issue by ladyredxiv** [daemitus/SomethingNeedDoing#114]
With retainer menu changes, we need a 13th select string command added into the clicks.

**Comment by MaximusMaraad** [comment]
> With retainer menu changes, we need a 13th select string command added into the clicks.

I was going to open this topic too kkkkkk

**Comment by BeetleLord** [comment]
Indeed, we can't select the option to exit retainer menus currently.

**Comment by WilliamW1979** [comment]
I already saw this problem, fixed it. I tested it and I am TRYING to send him the update right now.

**Comment by WilliamW1979** [comment]
Alright, I did a pull request to fix this. It does work because I am using it in developer mode thanks to not being able to update it for some reason on Dalamud's end. I just happened to have the fix on my end because I was working in developer mode because Dalamud is not updating a lot of plugins so I manually put some in like this one.

Just so you guys know, this wasn't an update for Something Needing Done. The update was for ClickLib to add more. You won't see the pull request in here because of that but don't worry, it is done and you should see the fix soon.

**Comment by WilliamW1979** [comment]
Oh, I made it go up to 14 strings for now in the pull request ... I figure I add one just in case.

**Comment by ladyredxiv** [comment]
Thank yoooou!!
